"""empty message

Revision ID: 605cc4c1a5d3
Revises: 
Create Date: 2025-09-23 00:16:54.099575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605cc4c1a5d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airbnb_guestpic', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('phone_last4', sa.String(length=4), nullable=True))
        batch_op.create_unique_constraint('uq_booking_listing_googleid', ['listing_id', 'google_calendar_id'])

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('airbnb_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('airbnb_zipcode', sa.String(length=15), nullable=True))
        batch_op.create_foreign_key('fk_listings_current_booking', 'bookings', ['booking_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jpeg', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('jpeg')
        batch_op.drop_column('security_question')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_listings_current_booking', type_='foreignkey')
        batch_op.drop_column('airbnb_zipcode')
        batch_op.drop_column('airbnb_address')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_booking_listing_googleid', type_='unique')
        batch_op.drop_column('phone_last4')
        batch_op.drop_column('airbnb_guestpic')

    # ### end Alembic commands ###
