"""empty message

Revision ID: 6e00a28f73ef
Revises: 605cc4c1a5d3
Create Date: 2025-09-25 00:17:37.022556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e00a28f73ef'
down_revision = '605cc4c1a5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_booking_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_listings_current_booking'), type_='foreignkey')
        batch_op.create_foreign_key('fk_listings_current_booking', 'bookings', ['current_booking_id'], ['id'], use_alter=True)
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_listings_current_booking', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_listings_current_booking'), 'bookings', ['booking_id'], ['id'])
        batch_op.drop_column('current_booking_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
