"""Add favorite_pet to User

Revision ID: 9568906c225b
Revises: 6e00a28f73ef
Create Date: 2025-09-29 23:56:21.806036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9568906c225b'
down_revision = '6e00a28f73ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_pet', sa.String(length=255), nullable=True))
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('favorite_pet')

    # ### end Alembic commands ###
