"""empty message

Revision ID: b3e8ca1b6bfe
Revises: b39068d860a3
Create Date: 2025-09-26 22:36:40.750194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e8ca1b6bfe'
down_revision = 'b39068d860a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_listings_current_booking', 'bookings', ['current_booking_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_listings_current_booking', type_='foreignkey')

    # ### end Alembic commands ###
